AWSTemplateFormatVersion: "2010-09-09"
Description: IAM user creation
Resources:
  Myuser:
    Type: AWS::IAM::User
    Properties:
      Groups:
        - DevOps-Team
      LoginProfile:
        Password: Samod11#
        PasswordResetRequired: No
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonDMSRedshiftS3Role
      # Path: String
      # PermissionsBoundary: String
      Policies:
        - PolicyDocument: {
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:CreateBucket",
                "s3:ListBucket",
                "s3:DeleteBucket",
                "s3:GetBucketLocation",
                "s3:GetObject",
                "s3:PutObject",
                "s3:DeleteObject",
                "s3:GetObjectVersion",
                "s3:GetBucketPolicy",
                "s3:PutBucketPolicy",
                "s3:GetBucketAcl",
                "s3:PutBucketVersioning",
                "s3:GetBucketVersioning",
                "s3:PutLifecycleConfiguration",
                "s3:GetLifecycleConfiguration",
                "s3:DeleteBucketPolicy"
            ],
            "Resource": "arn:aws:s3:::dms-*"
        }
    ]
}
          PolicyName: AmazonDMSRedshiftS3Role
      Tags:
        - Key: Name
          Value: Moddy933
        - Key: Env
          Value: Devops
      UserName: Moddy933
